# Generated by Django 2.2 on 2019-04-24 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Name')),
                ('ip_address', models.GenericIPAddressField(unique=True, verbose_name='IP Address')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
            },
        ),
        migrations.CreateModel(
            name='DeviceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.IntegerField(choices=[(0, 'CPU_USAGE'), (1, 'MEMORY_USAGE'), (2, 'DISK_SPACE_LEFT')], verbose_name='Data Type')),
                ('data', models.IntegerField(default=0, verbose_name='Value')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.Device', verbose_name='Device')),
            ],
            options={
                'verbose_name': 'Device Data',
                'verbose_name_plural': 'Device Data',
            },
        ),
    ]
