# Generated by Django 2.2 on 2019-04-26 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.IntegerField(verbose_name='Data Type')),
                ('comparison_type', models.IntegerField(choices=[(0, '='), (1, '>'), (2, '<')], verbose_name='Comparison')),
                ('comparison_value', models.FloatField(help_text='Either in % or in GB', verbose_name='Value')),
            ],
            options={
                'verbose_name': 'Alarm',
                'verbose_name_plural': 'Alarms',
            },
        ),
        migrations.CreateModel(
            name='DeviceAlarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_reported', models.DateTimeField(blank=True, null=True, verbose_name='Last reported')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('alarm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.Alarm', verbose_name='Alarm')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.Device', verbose_name='Device')),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.Notification', verbose_name='Notification')),
            ],
            options={
                'verbose_name': 'Device Alarm',
                'verbose_name_plural': 'Device Alarms',
            },
        ),
    ]
