# Generated by Django 2.2 on 2019-04-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_alarm_devicealarm'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicealarm',
            name='frequency',
            field=models.IntegerField(choices=[(300, '5 minutes'), (3600, 'hourly'), (86400, 'daily'), (604800, 'weekly'), (2592000, 'monthly')], default=3600, verbose_name='Frequency'),
        ),
    ]
