# Generated by Django 2.2 on 2019-04-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0003_devicealarm_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='data_type',
            field=models.IntegerField(choices=[(0, 'CPU_USAGE'), (1, 'MEMORY_USAGE'), (2, 'DISK_SPACE_LEFT')], verbose_name='Data Type'),
        ),
    ]
