# Generated by Django 2.2 on 2019-04-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0004_auto_20190426_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='comparison_type',
            field=models.IntegerField(choices=[(1, '>'), (2, '<')], verbose_name='Comparison'),
        ),
    ]
