# Generated by Django 2.2 on 2019-04-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0005_auto_20190426_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicealarm',
            name='frequency',
            field=models.CharField(choices=[('*/5 * * * *', '5 minutes'), ('0 * * * *', 'Hourly'), ('0 9 * * *', 'Daily at 9am'), ('0 9 * * 1', 'Weekly on Mondays'), ('0 9 1 * *', 'Monthly on 1st')], default='0 * * * *', max_length=30, verbose_name='Frequency'),
        ),
    ]
